create table SalesOrderHeader(
SalesOrderID int,   
RevisionNumber  int,
OrderDate smalldatetime,
DueDate smalldatetime,
ShipDate smalldatetime, 
Status  int,
OnlineOrderFlag int,
SalesOrderNumber varchar(20),   
PurchaseOrderNumber varchar(50),
AccountNumber   varchar(50),
CustomerID  int,
SalesPersonID int,  
TerritoryID  int,
BillToAddressID int,
ShipToAddressID int,
ShipMethodID int,   
CreditCardID int,   
CreditCardApprovalCode  varchar(50),
CurrencyRateID int, 
SubTotal numeric,     
TaxAmt  numeric,  
Freight numeric,  
TotalDue numeric, 
Comment varchar(50),
rowguid varchar(50),
ModifiedDate smalldatetime,
primary key (SalesOrderID),
Foreign key (CustomerID ) references Customer(CustomerID)
);
