Create table Product(
ProductID int,
Name nvarchar (50),  
ProductNumber varchar(20),  
MakeFlag int,   
FinishedGoodsFlag int,
Color nvarchar (20),  
SafetyStockLevel int,   
ReorderPoint int,   
StandardCost numeric(18,4), 
ListPrice numeric(18,4),    
Size nvarchar (6),    
SizeUnitMeasureCode nvarchar (20),
WeightUnitMeasureCode nvarchar (20),   
Weight numeric(18,4),   
DaysToManufacture int,  
ProductLine nvarchar (20),   
Class nvarchar (20),   
Style nvarchar (20),   
ProductSubcategoryID int,   
ProductModelID int,
SellStartDate smalldatetime,
SellEndDate smalldatetime,
DiscontinuedDate smalldatetime, 
rowguid nvarchar (50),
ModifiedDate smalldatetime,
PRIMARY KEY (ProductID)
);
